package view.admin;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import service.UserService;
import view.HomePage;
import view.Login;

public class QLUser extends javax.swing.JFrame {

    User user = null;
    DefaultTableModel defaultTableModel = null;
    UserService userService = null;

    public QLUser(User user) throws SQLException {

        this.user = user;
        userService = new UserService();

        initComponents();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) { //Cái này là để k cho sửa trực tiếp trên bảng
                return false;
            }
        };
        userTable.setModel(defaultTableModel);
        // Tạo hàng tiêu đề
        defaultTableModel.addColumn("Id");
        defaultTableModel.addColumn("Tên người dùng");
        defaultTableModel.addColumn("Số điện thoại");
        defaultTableModel.addColumn("Số dư");
        defaultTableModel.addColumn("Trạng thái");
        // Đổ dữ liệu vào bảng
        setTableData(userService.getAllUser());
    }

    // Hàm này dùng để đổ dữ liệu từng dòng
    private void setTableData(List<User> users) {
        for (User user : users) {
            String trangThai = user.getStatus() == 1 ? "Mở" : "Khóa";
            defaultTableModel.addRow(new Object[]{user.getId(), user.getName(),
                user.getPhoneNumber(), user.getSoDu(), trangThai});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        viewBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        addBT = new javax.swing.JButton();
        refreshBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        drawMoneyBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(userTable);

        viewBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        viewBT.setText("Xem chi tiết");
        viewBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTActionPerformed(evt);
            }
        });

        deleteBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        deleteBT.setText("Xóa");
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });

        addBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addBT.setText("Thêm mới");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        refreshBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        refreshBT.setText("Làm mới");
        refreshBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ NGƯỜI DÙNG");

        backBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        backBT.setText("Quay lại");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });

        drawMoneyBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        drawMoneyBT.setText("Rút tiền");
        drawMoneyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawMoneyBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBT)
                        .addGap(68, 68, 68)
                        .addComponent(viewBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBT)
                        .addGap(99, 99, 99)
                        .addComponent(drawMoneyBT))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBT)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refreshBT)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(refreshBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drawMoneyBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTActionPerformed
        // TODO add your handling code here:
        int row = userTable.getSelectedRow(); //Xác định hàng mà mình đã chọn
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn người dùng cần xem trước đi bạn ei", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 0)));
            try {
                new UserViewById(id, user).setVisible(true); // Chuyển qua trang xem
                this.dispose(); // Đóng trang hiện tại
            } catch (SQLException ex) {
                Logger.getLogger(QLUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_viewBTActionPerformed

    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
        int row = userTable.getSelectedRow(); //Xác định hàng mà mình đã chọn
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn người dùng cần xóa trước đi bạn ei", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION); //Xác nhận xóa

            if (confirm == 0) {
                int id = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 0)));
                try {
                    int rs = userService.deleteUser(id);
                    
                    defaultTableModel.setRowCount(0); // reset dữ liệu về 0
                    setTableData(userService.getAllUser()); // Gọi hàm đổ dữ liệu vào bảng
                } catch (SQLException ex) {
                    Logger.getLogger(QLUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteBTActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
        new UserAdd(user).setVisible(true); // Chuyển qua trang add
        this.dispose(); // Đóng trang hiện tại
    }//GEN-LAST:event_addBTActionPerformed

    private void refreshBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTActionPerformed
        // TODO add your handling code here:        
        try {
            defaultTableModel.setRowCount(0);
            setTableData(userService.getAllUser());
            JOptionPane.showMessageDialog(this, "Làm mới thành công", "Thông báo", JOptionPane.CLOSED_OPTION);
        } catch (SQLException ex) {
            Logger.getLogger(QLUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_refreshBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        try {
            new HomePage(user).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(QLUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backBTActionPerformed

    private void drawMoneyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawMoneyBTActionPerformed
        // TODO add your handling code here:
        int row = userTable.getSelectedRow(); //Xác định hàng mà mình đã chọn
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn người dùng cần rút tiền trước đi bạn ei", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 0)));
            int soDu = Integer.valueOf(String.valueOf(userTable.getValueAt(row, 3)));
            
            new AdminDrawMoneyUser(user, id, soDu).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_drawMoneyBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton backBT;
    private javax.swing.JButton deleteBT;
    private javax.swing.JButton drawMoneyBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBT;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewBT;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewButton1;
    // End of variables declaration//GEN-END:variables
}
